disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Wes Shaddix"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
 name = "Wes Shaddix"
 email = "wes@wshaddix.com"
 image = "img/coding-in-the-forest.png"
 imageQuality = 96
 headline = ""
 bio = ""
 links = [
   { email = "mailto:wes@wshaddix.com" },
   { github = "https://github.com/wshaddix" },
   { twitter = "https://twitter.com/wshaddix" }
   ]
